### ISSUE TITLE
Add filters to the high-level queries

### ISSUE THREAD

**Issue by jburos** [generable/rgeco#11]
Per https://github.com/generable/geco/issues/746, support filters on API calls

1. [ ] get_geco_subjects()
2. [ ] get_geco_biomarkers()
3. [ ] get_geco_doses()

Similarly, from @ericnovik :

Should we allow for more granular subsetting in calls to subjects, doses, and biomarkers? By default, these return a lot of data, which is not a problem now but may be unwieldy over time. For example, we could do something like:

```r
sub <- get_geco_subjects(project = "lommy",
                                 age_min = 20,
                                 age_max = 60,
                                 sex = female, ...)
```

**Comment by ericnovik** [comment]
Further subsetting seems useful. Is there a more general solution than listing out the columns in the call signature?
