### ISSUE TITLE
get_geco_biomarkers slow

### ISSUE THREAD

**Issue by ericnovik** [generable/rgeco#19]
Consider the following call:
```
bio <- get_geco_biomarkers(
  project = "lommy",
  measurement_name = "some_nonexistent_measurement_name"
)
```
The above will run for a long time and return a NULL set.

I propose the following:

1. Create a new function called `get_ measurement_names`. (Do we need `geco` inside function names? Just a question)
2. When calling `get_geco_biomarkers`, first check if the measurement name exists and return an error message if it does not.
3. Optionally, add indexes to the tables to make joins faster

**Comment by jburos** [comment]
Re-opening because it's still slow when querying a lot of biomarkers.

This is likely a combination of query response time & the (now-default) rolling merge with dosing data.
