### ISSUE TITLE
Document inference API methods

### ISSUE THREAD

**Issue by jburos** [generable/rgeco#68]
Listing here the functions whose documentation we want to review (most are minimally documented).

1. [x] `fetch_inference_dataset_info`: 
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_dataset.R#L2-L4) 
    - This queries the `/inferences/projectversion/{project_version_id}/dataset/attributes` endpoint
    - This returns a data.frame with information about the Datasets for which runs are available.
1. [x] `fetch_inference_data`:
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_dataset.R#L60-L62)
    - This hits the `/inferences/projectversion/{project_version_id}/run/{run_id}/dataset` endpoint for a run id
    - This returns a named list of dataframes containing the input data to the run. example: subjects, biomarkers, etc.
1. [x] `fetch_inference_quantiles`:
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_draws.R#L2-L4)
    - This hits all 4 quantiles endpoints, depending on user arguments:
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/quantiles/posterior/{parameter}`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/quantiles/posterior/{parameter}/predictive`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/quantiles/prior/{parameter}`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/quantiles/prior/{parameter}/predictive`
    - The function returns a data frame with one record per parameter dimension and quantile computed.
    - See also `format_quantiles_as_widths` function, to convert this from per-quantile to per-credible-interval format.
    - ~~Also, remember, per #65, this function has not been updated yet to reference the new quantiles endpoints. It still looks for values using `parameter_name == "summarized_{parameter_name}"`.~~ This was fixed prior to 05/24/2021.
1. [ ] `format_quantiles_as_widths`
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/utils_draws.R#L55)
    - This formats the quantiles data from one-record-per-quantile to record per credible interval width (matched quantiles with `.lower`, `.upper`, `median`, and `.width` fields).
    - Here, an example would be very helpful to provide.
1. [x] `fetch_inference_draws`:
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_draws.R#L2-L4)
    - This hits all 4 draws endpoints, depending on user arguments:
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/draws/posterior/{parameter}`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/draws/posterior/{parameter}/predictive`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/draws/prior/{parameter}`
        - `/inferences/projectversion/{project_version_id}/run/{run_id}/draws/prior/{parameter}/predictive`
    - The function returns a data frame that is (almost) in `posterior_draws_df` format. 
    - The dataframe contains one record per chain (`.chain`), draws (`.iteration`), and parameter dimension(s).
    - Here, we should provide an example or vignette on using `posterior` methods to summarize sampling quality. We should also comment if the draws are paginated.
1. [x] `fetch_inference_models`
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_models.R#L2-L3)
    - This hits the `/inferences/projectversion/{project_version_id}/models` endpoint
    - It returns a data.frame with attributes per model for which at least one run has completed in this project version.
    - Note: this file contains the `fetch_inference_model_pars` method, which will be deprecated as the endpoint will be removed.
1. [x] `fetch_inference_runs`
    - [link to code](https://github.com/generable/rgeco/blob/issue-62-inference-quantiles/R/inference_runs.R#L2-L4)
    - This hits the `/inferences/projectversion/{project_version_id}/runs` endpoint
    - This returns a data.frame containing information about each model run for the projectversion, such as model_id, dataset_id, number of draws, execution environment, and a summary of the run diagnostics from the posterior fit.
    - We may consider modifying this function to pull in the most important features from the models & dataset/attributes endpoints for a complete picture. Or, modifying the "print" method to summarize the runs in a user-friendly way.

**Comment by syclik** [comment]
Here's the full list of exported functions, in alphabetical order:

1. [ ] `extract_subsample_info`
1. [ ] `fetch_biomarkers`
1. [ ] `fetch_doses`
1. [ ] `fetch_events`
1. [ ] `fetch_inference_data`
1. [ ] `fetch_inference_dataset_info`
1. [ ] `fetch_inference_draws`
1. [ ] `fetch_inference_models`
1. [ ] `fetch_inference_quantiles`
1. [ ] `fetch_inference_runs`
1. [ ] `fetch_labs`
1. [ ] `fetch_measurement_names`
1. [ ] `fetch_pkpd`
1. [ ] `fetch_projects`
1. [ ] `fetch_projectversions`
1. [ ] `fetch_subjects`
1. [ ] `format_quantiles_as_widths`
1. [ ] `login`
1. [ ] `prep_km_data`
1. [ ] `prep_pkpd_data`
1. [ ] `sample_groups`

**Comment by syclik** [comment]
Functions to change:
- [ ] `fetch_projects` -> `list_projects`
- [ ] `fetch_measurement_names` -> `list_measurement_names`

**Comment by syclik** [comment]
error handling issue:
```
> z = fetch_inference_quantiles('sld_sigma', project = 'impower150-validation')
INFO [2021-05-24 11:12:53] Project version id set to ef164d08-7e72-47d7-b9a9-c9fc7c8ed746
INFO [2021-05-24 11:12:53] Data were last updated 2021-03-08: Assignment of subjects to analysis sample from data provided 2/3/2021 (Sample of data locked on 15 Sep 2017)
Error: Problem with `filter()` input `..1`.
x object 'run_parameters' not found
ℹ Input `..1` is `purrr::map_lgl(run_parameters, ~param_name %in% .x)`.
Run `rlang::last_error()` to see where the error occurred.
> 

(runs %>% slice(1) %>% pull(run_quantiles))[[1]] %>% names


```

**Comment by jburos** [comment]
Thanks @syclik. This is because the query is looking for a latest run with
that parameter, and I suspect the structure of the runs info has changed.

I recommend we just modify this to require a run id. That will be simpler.

We should also probably insert a test project and data for testing
purposes.
