### ISSUE TITLE
Provide convenience functions for accessing standard predictive quantities & parameters

### ISSUE THREAD

**Issue by jburos** [generable/rgeco#77]
I'm thinking to create the following functions:

* [x] `fetch_predicted_biomarkers`, with arguments:
    - `level = c('subject', 'trialarm', 'overall')`
    - `include_noise = TRUE|FALSE`
    - `return = c('draws', 'quantiles', 'median')`
* [x] `fetch_predicted_survival`, with arguments:
    - `level = c('subject', 'trialarm', 'overall')`
    - `return = c('draws', 'quantiles', 'median')`
* [x] `fetch_predicted_hazard`, with arguments:
    - `level = c('subject', 'trialarm', 'overall')`
    - `return = c('draws', 'quantiles', 'median')`
* [x] `fetch_biomarker_params` (Note: this fetches f, kg, and ks)
    - `level = c('subject', 'trialarm', 'overall')`
    - `return = c('draws', 'quantiles', 'median')`
* [x] `fetch_association_state`
    - `level = c('subject', 'trialarm', 'overall')`
    - `return = c('draws', 'quantiles', 'median')`
* [ ] `fetch_hazard_betas`
    - `level = c('overall')`
    - `return = c('draws', 'quantiles', 'median')`
* [ ] `fetch_hazard_ratio`: 
    - `level = c('subject', 'trialarm')`
    - `return = c('draws', 'quantiles', 'median')`
    - `control_arm = c()`

Alternately, we could implement 2 of all of these: `fetch_quantiles_hazard_ratio` & `fetch_draws_hazard_ratio`, for example. 

Either way, the functions would be implemented in a few highly-reusable parts:
1. one function to get a list of parameter names from type, level & other arguments. 
2. a call to `fetch_draws` or `fetch_quantiles` to get the results
3. any post-processing necessary to transform or filter returned objects (e.g. convert_quantiles_to_widths)

I would also like the default value of `return = c('draws', 'quantiles', 'median')` to be consistent across all the methods. We should decide what the default should be. Also we should decide if we want to convert to intervals from quantiles by default, or make this (e.g. `interval`) an option in the `return` argument. @ericnovik suggested a default value of `median`, with an informative message that this can be changed.

The default level however should vary depending on the method. For example, hazard_ratio & survival will have default to trial_arm, whereas biomarkers will default to subject.

**Comment by ericnovik** [comment]
Those would be very helpful, thanks.
